version: "2.4"
services:
  server: 
    image: "python:3.9-alpine"
    ports:
      - 20000:20000
    volumes:
      - ./vagrant/packages:/packages
    entrypoint: python
    command: "-m http.server 20000 --directory /packages --bind 0.0.0.0"
    cpu_count: 1
    cpu_percent: 20
    mem_reservation: 128m
    read_only: true